services:

  db:
    image: mysql:8.0.31-oracle
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD_DES
      - MYSQL_DATABASE=$MYSQLDB_DATABASE_DES
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT_DES
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network

  api:
    build: api
    restart: unless-stopped
    environment:
      - API_PORT=$API_PORT
      - API_DEBUG=$API_DEBUG
      - POKEAPI_URL=$POKEAPI_URL
    networks:
      - app-network
    ports:
      - $API_PORT:$API_PORT
    volumes:
      - ./api:/api

  app:
    depends_on:
      - db
      - api
    build: app
    restart: on-failure
    environment:
      - APP_CONTAINER_NAME_DES=$APP_CONTAINER_NAME_DES
      - SPRING-DATASOURCE-USERNAME=$MYSQLDB_USER_DES
      - SPRING-DATASOURCE-PASSWORD=$MYSQLDB_ROOT_PASSWORD_DES
      - SPRING-DATASOURCE-DRIVER-CLASS-NAME=$SPRING_DATASOURCE_DRIVER_CLASS_NAME_DES
      - SPRING-JPA-HIBERNATE-DLL-AUTO=$SPRING_JPA_HIBERNATE_DLL_AUT_DES
      - SPRING-JPA-SHOW-SQL=false
      - SERVER-PORT=$SPRING_DOCKER_PORT_DES
      - SPRING-DATASOURCE-URL=jdbc:mysql://db:$MYSQLDB_DOCKER_PORT_DES/$MYSQLDB_DATABASE_DES?useSSL=false&allowPublicKeyRetrieval=true
      - API_URL=$API_URL
    networks:
      - app-network
    ports:
      - $SPRING_LOCAL_PORT_DES:$SPRING_DOCKER_PORT_DES
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./.m2:/home/nonroot/.m2
      - ./app/src/main/resources:/app/resources
      - type: bind
        source: ./certificates
        target: /certificates
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          memory: 1G

networks:
  app-network:
    driver: bridge

volumes:
  db:
