spring.application.name=${APP_CONTAINER_NAME_DES}
#Indica el driver/lib para conectar java a mysql
spring.datasource.driver-class-name=${SPRING-DATASOURCE-DRIVER-CLASS-NAME}

#Url donde esta el servicio de tu mysql y el nombre de la base de datos
spring.datasource.url=${SPRING-DATASOURCE-URL}

#Usuario y contrasena para tu base de datos descrita en la linea anterior
spring.datasource.username=${SPRING-DATASOURCE-USERNAME}
spring.datasource.password=${SPRING-DATASOURCE-PASSWORD}

#[opcional]Imprime en tu consola las instrucciones hechas en tu base de datos.
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto=${SPRING-JPA-HIBERNATE-DLL-AUTO}
#habilitamos la pagina de error generico
server.port=${SERVER-PORT}

############################################
# Configuración específica de la práctica

app.api.url=${APP_API_URL}
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=file:/app/resources/templates/
spring.web.resources.static-locations=file:/app/resources/static/
spring.devtools.livereload.enabled=true
